### ISSUE TITLE
When I click the question mark, and afterwards close the full screen, the text is not placed properly

### ISSUE THREAD

**Issue by pascalalferink** [semnijenhuis/3D-ArcGisProject#55]

**Comment by pascalalferink** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/1e2e33db-b032-406d-8334-a45c21f5eb28)

**Comment by semnijenhuis** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/f7416810-95bf-41a7-8273-f0d793132342)
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/0767070a-3ab9-457b-96ee-c7fe5df77fb5)

Issue resolved, now the screen closes automatically
