### ISSUE TITLE
When I click on a reaction while I am not in fullscreen-modus, the reaction panel is too large for the 3d view

### ISSUE THREAD

**Issue by pascalalferink** [semnijenhuis/3D-ArcGisProject#56]

**Comment by pascalalferink** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/3b0217de-95b5-4b9d-b1f3-ca6307f1de0a)

**Comment by pascalalferink** [comment]
The panel is also placed over the menu bar with the bookmarks and the button

**Comment by semnijenhuis** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/51b51e06-59c3-4492-af41-652fcaeb22b1)

Reponse list now stays inside its div
