### ISSUE TITLE
The menubar is smaller than it should be. Also on the mobile devices the logo doesn't have any padding

### ISSUE THREAD

**Issue by pascalalferink** [semnijenhuis/3D-ArcGisProject#57]

**Comment by pascalalferink** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/92c78c9f-c520-4332-91df-9dbbfb9bdb0f)

**Comment by semnijenhuis** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/a4e3877a-8eb7-4b6d-b298-35cafa45c212)

Overlap issue has been resolved
