### ISSUE TITLE
When the scene is white, you can't see where the bookmark bar is.

### ISSUE THREAD

**Issue by pascalalferink** [semnijenhuis/3D-ArcGisProject#60]

**Comment by pascalalferink** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/2c049663-c3ed-4f93-8d5e-2ae74c00529c)

**Comment by semnijenhuis** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/89bed3de-aa27-49ff-a0bd-3151f6bdef11)

Issue now resolved with changes to the css
