### ISSUE TITLE
When there is no response form attached the the webscene, the page crashes

### ISSUE THREAD

**Issue by pascalalferink** [semnijenhuis/3D-ArcGisProject#62]

**Comment by pascalalferink** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/e00a84b8-2310-42b4-8e15-1dbd1fe1d279)

**Comment by semnijenhuis** [comment]
![Schermafbeelding 2024-06-20 160150](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/374e9218-750b-402b-ba22-489ac8f7540c)

Issue has now been resolved
