### ISSUE TITLE
De pijltjes bij de menubar onderin zijn niet digitoegankelijk

### ISSUE THREAD

**Issue by pascalalferink** [semnijenhuis/3D-ArcGisProject#65]
Gebruikers zonder muis kunnen niet bij deze pijltjes komen: 

![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/ccbb32ca-6fc4-4930-89d4-2af3d677af24)

je kunt dit fixen door er een button of link van te maken

**Comment by semnijenhuis** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/063d7f77-57d1-4e21-966e-b82e70d9adb0)

You can now tab the arrows
