### ISSUE TITLE
The widgets you can configure in Wagtail doesn't seem to work

### ISSUE THREAD

**Issue by pascalalferink** [semnijenhuis/3D-ArcGisProject#66]
You can configure these widgets, but I can't see them.
Two possible solutions:
1 remove the options from wagtail
2 show the widgets in on the portal

![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/a4e2abb9-b76a-4b11-9a9b-113e4fff7f65)

**Comment by semnijenhuis** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/33a65dcb-b02e-44e5-8b2b-c9d8bd8605d4)

widgets are also now back
