### ISSUE TITLE
The logo has no padding

### ISSUE THREAD

**Issue by pascalalferink** [semnijenhuis/3D-ArcGisProject#67]
In #57  you fixed that the fullscreen isn't on top of the header menu.
1 issue remains and there is a new issue:

1. There isn't any padding above and below the logo (see screenshot 1)
2. When the menu is expanded the main button  is on top of the menu (screenshot 2)

![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/15600180-31ba-485d-8b0b-788d6d841dab)

![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/13336728/e75841a6-f383-4ff4-9dc8-4b31b8b94635)

**Comment by semnijenhuis** [comment]
![Image](https://github.com/semnijenhuis/3D-ArcGisProject/assets/59063331/065d0a31-6215-4887-b85e-4d216d40c058)

Padding added back again
